### ISSUE TITLE
Guide "Reinforcement Learning: Deep Q-Networks" always asserts

### ISSUE THREAD

**Issue by mushketer888** [ml4a/ml4a-guides#1]
Hi!
You have very useful lessons/guides about machine learning! (i could tell yours are the best)
But while trying to learn example from "Reinforcement Learning: Deep Q-Networks" code always asserts at: 
            # debug, "this should never happen"
            assert not np.array_equal(state, next_state)

Strange...It looks like environment state is not changing?
When commenting asserts i dont have "wins" at all (this is obvious of course)
Why this can happen and what to do?
You can see code here(at my fork):
https://github.com/mushketer888/ml4a-guides/tree/master/examples/deepqnetwork

Thanks

**Comment by frnsys** [comment]
hey, thanks for bringing this up, I'll look into it. do you know which assertion it happens at? there are two, one inside `_prep_batch` and one inside the training loop.
