### ISSUE TITLE
Q learning

### ISSUE THREAD

**Issue by singlasahil14** [ml4a/ml4a-guides#11]
How does explore = 0 imply that the agent is not getting trained? Ideally the _learn function will still be called and the agent will learn. Is it an error or some flaw in my understanding?
<img width="837" alt="screen shot 2016-12-14 at 2 20 42 pm" src="https://cloud.githubusercontent.com/assets/6660192/21175487/886361e6-c208-11e6-94ff-0f353176cd1e.png">

**Comment by frnsys** [comment]
yes, the agent does get trained there. that could be clarified as "before training" instead of "without training" - I'll update it in a sec

**Comment by frnsys** [comment]
let me know if that's clearer!

**Comment by singlasahil14** [comment]
Yes its clearer. Thank you 👍
