### ISSUE TITLE
No module named blessings

### ISSUE THREAD

**Issue by singlasahil14** [ml4a/ml4a-guides#12]
<img width="753" alt="screen shot 2016-12-14 at 8 40 55 pm" src="https://cloud.githubusercontent.com/assets/6660192/21187382/bc04562e-c23d-11e6-9b28-6ef8e89e69a9.png">
Its showing no module blessings installed. Even though I do have blessings installed. python -c "import blessings" doesn't show any error. Is this a bug?

**Comment by genekogan** [comment]
do you have two separate versions of python installed on your system?  if so, you have blessings installed in one, but jupyter/ipython pointing to the other.

**Comment by singlasahil14** [comment]
Fixed! Thank you 👍
