### ISSUE TITLE
data for seq2seq moved

### ISSUE THREAD

**Issue by beaunorgeot** [ml4a/ml4a-guides#13]
Hi Guys. Thanks for putting all this together. In going through your seq2seq notebook, it seems that the en_de_corpus data you prepped for it no longer lives where the link points (which was assests/en_de_tatoeba.json)

It now lives: https://raw.githubusercontent.com/ml4a/ml4a-guides/master/data/en_de_corpus.json

**Comment by frnsys** [comment]
thanks for pointing this out, i'll fix this now.
