### ISSUE TITLE
Unable to load the network in reverse image search

### ISSUE THREAD

**Issue by mathildebuenerd** [ml4a/ml4a-guides#17]
I have an issue with the Reverse image search notebook.
When I try to load the VGG16 (or VGG19) network with
`model = keras.applications.VGG16(weights='imagenet', include_top=True)`
the download starts but always gets stuck (without any error) before the end and I don't know why.

So I tried to download it directly from https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels.h5, put it in the myusername/.keras/models folder and then use
`model = keras.models.load_model(pathtothefile)`
in order to define the model but it doesn't find the file and I am not even sure that this is supposed to work.

**Comment by genekogan** [comment]
this is likely an issue with Keras. I've seen the download get stuck before. you may need to try to find the half-download and delete it by force, that might reset it and work the next time.

**Comment by mathildebuenerd** [comment]
finally it worked today by replacing the half-download network with the one downloaded from the browser. thanks!
