### ISSUE TITLE
Windows Python 3, hard work to get running

### ISSUE THREAD

**Issue by YanYas** [ml4a/ml4a-guides#18]
Hi, I really like your project but I find it very difficult to get running on Windows. 

I navigated to the Image t-SNE example from the 'guides' page and saw it was a notebook.  '.sh' won't necessarily work. I copied and pasted each line into cmd to put them in action.

I installed all the dependencies and having bumped into errors a few more that were not mentioned at the top of the page (matplotlib, Pillow), but I then the directory the python code looks for isn't there. 

Changing that directory to a subfolder in categories get "[Errno] 13: Permission denied."
Despite changing the access permissions to those files I still get the same error. Perhaps this is a uniquely Windows issue.

I'm currently trying to run this example using a docker, which is taking a while to install. It slso means I am using another 1.2GB of SSD space. Its Friday night. I'm sat staring through my fingers.

I am under the impression that you are using Python 2.7 on a Mac, which is why some these lines of code are failing for me. I think you should clarify all of the dependencies required, make a helper .py file that includes them, or make Docker the only option, though I would rather run your work natively in Windows so its easier to extend to my own projects. As a matter of personal preference I would prefer you use Python 3.x too, but beggars can't be choosers, 

Thanks

**Comment by genekogan** [comment]
sorry for all the trouble. nobody is actively developing this on windows, so some issues like the ones you describe don't get caught. one thing you can do is to use docker instead, as we provide a Dockerfile in the main repo. if you are able to contribute a PR that makes this easier to use in windows, that would also be highly appreciated and useful for others going through the same thing as you.

**Comment by YanYas** [comment]
Hi Gene,

I appreciate that this isn't the easiest sort of project to develop across
platforms. Part of my frustartion was in actually getting docker working
nicely. It ate up around 5GB of harddrive that's nearing capacity, but its
just a grumble, I just need to get more space. I'd like to look into it
actually (the PR). I'm off this topic at the moment but I'll look into it
later in the week.

Thanks again

H
