### ISSUE TITLE
No module named processing

### ISSUE THREAD

**Issue by juanikok93** [ml4a/ml4a-guides#53]
Hi
I've been trying to use the dataset_utils.py file to use on my preprocessing, but when i run it the following happens:

```
Traceback (most recent call last):
  File "dataset_utils.py", line 71, in <module>
    from processing import *
ModuleNotFoundError: No module named 'processing'
```

I ran it in my local machine, and also in a machine in paperspace, as well in a gradient notebook. Nowhere can I find such module, and when I try to pip install it:

```
# pip install processing
Collecting processing
  Downloading https://files.pythonhosted.org/packages/3b/2d/a6f17cc99d9c45c33eb3eccd6999505d9197b31f0845a845919032262a01/processing-0.52.zip (178kB)
    100% |████████████████████████████████| 184kB 9.9MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wiup4irl/processing/setup.py", line 12
        raise ValueError, 'Versions of Python before 2.4 are not supported'
                        ^
    SyntaxError: invalid syntax
```
What I'm I missing? it seems to be working fine for other people. Thanks in advance

**Comment by Paps90** [comment]
same error

**Comment by genekogan** [comment]
the `processing` module is inside the same folder. run from there.
https://github.com/ml4a/ml4a-guides/blob/master/utils/processing.py
