### ISSUE TITLE
DQN guide: game.render() is blank

### ISSUE THREAD

**Issue by genekogan** [ml4a/ml4a-guides#6]
game.render() seems to draw a blank screen for me in the DQN guide. i stepped through the guide and pushed the output to the repo so pull first. maybe this is a 2.7/3 discrepancy again?

**Comment by frnsys** [comment]
yeah there's a line in the guide noting that the game won't render in a notebook:

> Note that this needs to be run in the terminal in order to visualize the game.

I haven't figured out a good way of doing that kind of rendering in a notebook (replacing old content and updating with new content) but I'm open to suggestions!

**Comment by genekogan** [comment]
i've commented it out in the notebook and added that note. via [https://github.com/ml4a/ml4a-guides/commit/64ec56ede6ba83fcca5c8f2fa3df885faf2ff19d](https://github.com/ml4a/ml4a-guides/commit/64ec56ede6ba83fcca5c8f2fa3df885faf2ff19d)
