### ISSUE TITLE
'varying lines' image doesn't appear/load

### ISSUE THREAD

**Issue by ggaabe** [ml4a/ml4a-guides#7]
lines.svg in fundamentals.ipynb does not appear to exist/load.

**Comment by frnsys** [comment]
strange, seems to be loading fine for me:

![2016-10-07-160318_1201x772_scrot](https://cloud.githubusercontent.com/assets/1059947/19203853/95d13380-8ca7-11e6-92e2-bd34d10d3917.png)

how are you accessing the notebook? I don't thiink any of the assets will load if you view the notebooks in github.

**Comment by ggaabe** [comment]
I'm running it on a notebook locally. It doesn't appear when run locally or on github. Is it possible that the images are cached for you?
<img width="1010" alt="screen shot 2016-10-07 at 3 10 07 pm" src="https://cloud.githubusercontent.com/assets/5441185/19204101/78216b2c-8ca0-11e6-93dc-4840fbc0645f.png">

**Comment by frnsys** [comment]
hmm...it doesn't seem to be cached. are the other images loading fine?

**Comment by ggaabe** [comment]
None of the images are loading for me

**Comment by frnsys** [comment]
ah - where are you starting your notebook server? you should start it in the repo root.

**Comment by ggaabe** [comment]
Ah! That fixed it, thank you.
